/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Mon Jan 09 11:48:28 2017. */

#include "fkcomms.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t fkcomms_Field_fields[5] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fkcomms_Field, type, type, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, fkcomms_Field, i32, type, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, fkcomms_Field, u32, i32, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, fkcomms_Field, f32, u32, 0),
    PB_LAST_FIELD
};

const pb_field_t fkcomms_Message_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, fkcomms_Message, time, time, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, fkcomms_Message, id, time, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, fkcomms_Message, fields, id, &fkcomms_Field_fields),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
